language: go
go:
  - master
  - 1.7.4
before_script:
  - go vet ./...
install:
  - wget https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm -O ./gpm
  - chmod +x ./gpm
  - ./gpm install
  - go install